apiVersion: v1
kind: Service
metadata:
  name: simflow
  namespace: simflow
  labels:
    app: simflow
spec:
  type: LoadBalancer
  selector:
    app: simflow
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
